# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackbuzz < Formula
  desc "CLI tool for Slack messaging, channel management, and search"
  homepage "https://github.com/triptechtravel/slackbuzz-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.3.0/slackbuzz_darwin_amd64.tar.gz"
      sha256 "a3cfc8d80a11ce52e96808435fbaf35bcbb519e42702d57f63cc368fb013b1c2"

      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.3.0/slackbuzz_darwin_arm64.tar.gz"
      sha256 "f1fd4d700deb1b1d46f52c195968789a4f6167d9b5de565a6dba622b6fa91187"

      def install
        bin.install "slackbuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.3.0/slackbuzz_linux_amd64.tar.gz"
      sha256 "99b7f09d37aa30592b3889b389790fa0c122189e9ddab8b7d4377b63f76906a1"
      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.3.0/slackbuzz_linux_arm64.tar.gz"
      sha256 "bf5c1efe61ea81a9b35dc8671e744c4a4600927cc13cf21c202c996215252307"
      def install
        bin.install "slackbuzz"
      end
    end
  end

  test do
    system "#{bin}/slackbuzz", "version"
  end
end
