# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clickup < Formula
  desc "CLI tool for ClickUp task management with GitHub integration"
  homepage "https://github.com/triptechtravel/clickup-cli"
  version "0.24.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.24.0/clickup_darwin_amd64.tar.gz"
      sha256 "2679fe26be82e6bb77f9d9b2ce37533c1673b8f66de1eae83fb235269438ffc9"

      define_method(:install) do
        bin.install "clickup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.24.0/clickup_darwin_arm64.tar.gz"
      sha256 "fcfa5514e29c0786f97094e75e2b535279f4543902761a18231bf657e7effda5"

      define_method(:install) do
        bin.install "clickup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.24.0/clickup_linux_amd64.tar.gz"
      sha256 "8c4cd5eefbb915b3672b5de954c32235a1509b8a155f01d90d122da3a771bae8"
      define_method(:install) do
        bin.install "clickup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.24.0/clickup_linux_arm64.tar.gz"
      sha256 "7cbb44b77c8a1dc1d88927b5b75773329c0293cebef4f69d5d7b29fcc2bf81b7"
      define_method(:install) do
        bin.install "clickup"
      end
    end
  end

  test do
    system "#{bin}/clickup", "version"
  end
end
