# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clickup < Formula
  desc "CLI tool for ClickUp task management with GitHub integration"
  homepage "https://github.com/triptechtravel/clickup-cli"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.13.0/clickup_darwin_amd64.tar.gz"
      sha256 "f374743caad5a854570c61cac76c0689b8882e44b44fc3eb1abfca3f4df193c3"

      define_method(:install) do
        bin.install "clickup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.13.0/clickup_darwin_arm64.tar.gz"
      sha256 "bbca0bb82605c14cdb728223e756a46c0f4fbf6bb54aaad238ca186e34ff6322"

      define_method(:install) do
        bin.install "clickup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.13.0/clickup_linux_amd64.tar.gz"
      sha256 "ee26a1087af81cce9e97fcc752ac8c4096ca8b0186bc87118cbc86362d3e1744"
      define_method(:install) do
        bin.install "clickup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/clickup-cli/releases/download/v0.13.0/clickup_linux_arm64.tar.gz"
      sha256 "bd9a5672a0f00ff1cbd7454c91516a7d3934e07393570cae25aca044e83c54db"
      define_method(:install) do
        bin.install "clickup"
      end
    end
  end

  test do
    system "#{bin}/clickup", "version"
  end
end
