# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackbuzz < Formula
  desc "CLI tool for Slack messaging, channel management, and search"
  homepage "https://github.com/triptechtravel/slackbuzz-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.1.0/slackbuzz_darwin_amd64.tar.gz"
      sha256 "7e212142ada4c2d6435a334b709ca5a9a1900b63b7bb6c39c7a8c4de62d0a539"

      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.1.0/slackbuzz_darwin_arm64.tar.gz"
      sha256 "4942fbd781ca45e199af6fd58c0ea5dbb84461b3b32797b85934dc6f26674333"

      def install
        bin.install "slackbuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.1.0/slackbuzz_linux_amd64.tar.gz"
      sha256 "c492b08139a288822a9bc68975d8d230c514635ccb4831052e92efef08f08eaa"
      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.1.0/slackbuzz_linux_arm64.tar.gz"
      sha256 "04f14d1e5ad7ce1184028addbc7bcc81fc0d8e3ee1182d1ae41aa4927edcf5f0"
      def install
        bin.install "slackbuzz"
      end
    end
  end

  test do
    system "#{bin}/slackbuzz", "version"
  end
end
