# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackbuzz < Formula
  desc "CLI tool for Slack messaging, channel management, and search"
  homepage "https://github.com/triptechtravel/slackbuzz-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.2.0/slackbuzz_darwin_amd64.tar.gz"
      sha256 "438a4659d31a72b5b665706e9b487c6790f1c1b6776f2846a4cff7320618228f"

      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.2.0/slackbuzz_darwin_arm64.tar.gz"
      sha256 "f3c4c9fdbb333f475ab8e90350dc19558695a8dc8155ea5eca1be315e973f2b8"

      def install
        bin.install "slackbuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.2.0/slackbuzz_linux_amd64.tar.gz"
      sha256 "fbefb9df228d33555f9e4f12d892d5921d21f5f615a6a8f23c3ae933323abd3a"
      def install
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.2.0/slackbuzz_linux_arm64.tar.gz"
      sha256 "32f110f2453d58d1f862121d20e87f97224afbff6e23cb3ea256f3360480a8a3"
      def install
        bin.install "slackbuzz"
      end
    end
  end

  test do
    system "#{bin}/slackbuzz", "version"
  end
end
