# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackbuzz < Formula
  desc "CLI tool for Slack messaging, channel management, and search"
  homepage "https://github.com/triptechtravel/slackbuzz-cli"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.10.0/slackbuzz_darwin_amd64.tar.gz"
      sha256 "e333ec1d72fcf1c69d4de3a497eb57b5315303c8938f12330e33f16d6c71c4af"

      define_method(:install) do
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.10.0/slackbuzz_darwin_arm64.tar.gz"
      sha256 "d5b3c162eaf8cddce8e4c599e0e84a7fc5f0f2d25e87fbb2eef3987bc7d6c472"

      define_method(:install) do
        bin.install "slackbuzz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.10.0/slackbuzz_linux_amd64.tar.gz"
      sha256 "8fae8d18d58f08234d699456e0d9292ccb50d4ec06a8aa5f53586be4a79a3aaf"
      define_method(:install) do
        bin.install "slackbuzz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triptechtravel/slackbuzz-cli/releases/download/v0.10.0/slackbuzz_linux_arm64.tar.gz"
      sha256 "6ce4adf1abe438b3172a823dca844d8470d62a2d4981f91f629fc5e9c774bfce"
      define_method(:install) do
        bin.install "slackbuzz"
      end
    end
  end

  test do
    system "#{bin}/slackbuzz", "version"
  end
end
